config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  scope '/admin' do
    resources :recepts
  end
  post 'main/search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
# == Schema Information
#
# Table name: cities
#
#  id         :integer          not null, primary key
#  name       :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class City < ApplicationRecord
  belongs_to :user
end

app/models/recept.rb
# == Schema Information
#
# Table name: recepts
#
#  id               :integer          not null, primary key
#  link             :string
#  form_param       :string
#  current          :string
#  max              :string
#  min              :string
#  probability      :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  id_or_name       :string
#  name_input_field :string
#

class Recept < ApplicationRecord
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ApplicationRecord
  has_many :cities

  before_create do
    self.name = 'Noname'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :current_user

  def index
    @recepts = Recept.all.reverse
    @cities = {}
    @user.cities.map(&:name).each do |city|
      @weather = {}
      @recepts.each do |recept|
        a = Mechanize.new
        page = a.get(recept.link)

        parsered_page = if recept.link.include?('sinoptik.ua')
                          page.form_with(action: recept.id_or_name) do |f|
                            f.search_city = city
                          end.submit.parser
                          # else #recept.link.include?('meteoblue.com')
                          #   page.form_with(action: recept.id_or_name) do |f|
                          #                                     f.query = city
                          #                                   end.submit.parser
                        end
        metrics = {}
        puts a

        begin
          metrics[:min] = parsered_page.at_css(recept.min).text
          puts metrics[:min]
          metrics[:max] = parsered_page.at_css(recept.max).text
          metrics[:current] = parsered_page.at_css(recept.current).text
          metrics[:probability] = parsered_page.at_css(recept.probability).text
        rescue
        end

        @weather[recept.link] = metrics
      end

      @cities[city] = @weather
    end

    puts @cities # byebug
  end

  def search
    @city = City.new(name: params[:city])
    @user.cities << @city

    respond_to do |format|
      format.html { render || redirect_to(wherever(you(need(it)))) }
      format.js
    end
  end

  private

  def current_user
    session[:user_id] ||= User.create.id
    @user = User.find(session[:user_id])
  end
end

app/controllers/recepts_controller.rb
class ReceptsController < ApplicationController
  def index
    @recepts = Recept.all
  end

  def create
    @recept = Recept.create incom_recept
  end

  def new
    @recept = Recept.new
  end

  def edit; end

  def destroy; end

  private

  def incom_recept
    params.require(:recept).permit(:link,
                                   :form_param,
                                   :id_or_name,
                                   :current,
                                   :min,
                                   :max,
                                   :probability,
                                   :name_input_field)
  end
end

app/helpers/admin/recepts_helper.rb
module Admin::ReceptsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wc</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<%= form_tag('/main/search', remote: true) do %>
  <%= label_tag(:city, 'search for cities') %>
  <%= text_field_tag(:city) %>
  <%= submit_tag('search') %>
<% end %>

user id is: <%= @user %>
<br>
<%= link_to 'Add new recept', new_recept_path %>

app/views/main/search.js.erb
alert('works fine!');

app/views/recepts/index.html.erb
<% @recepts.each do |recept| %>
<nl>
  <li><%= recept.link %></li>
</nl>
<% end  %>

app/views/recepts/new.html.erb
Form

<%= form_for @recept do |f| %>
  <ul>
    <li><%= f.label :link %></li>
    <li><%= f.text_field :link %></li>
    <li><%= f.label :form_param %></li>
    <li><%= f.select(:form_param, [%w(id id),%w(name name), %w(action action)]) %></li>
    <li><%= f.label :id_or_name %></li>
    <li><%= f.text_field :id_or_name %></li>
    <li><%= f.label :name_input_field %></li>
    <li><%= f.text_field :name_input_field %></li>
    <li><%= f.label :current %></li>
    <li><%= f.text_field :current %></li>
    <li><%= f.label :min %></li>
    <li><%= f.text_field :min %></li>
    <li><%= f.label :max %></li>
    <li><%= f.text_field :max %></li>
    <li><%= f.label :probability %></li>
    <li><%= f.text_field :probability %></li>
    <br>
    <li><%= f.submit %></li>
  </ul>

<% end %>